sensors:
  - id: 1
    name: airspeed_sensor
    metrics:
      - name: airSpeed
        unit: m/s
        value: 120.5
      - name: altitude
        unit: m
        value: 1000.0
      - name: engineTemperature
        unit: C
        value: 85
      - name: fuelLevel
        unit: "%"
        value: 60
      - name: batteryVoltage
        unit: V
        value: 12

  - id: 2
    name: altitude_sensor
    metrics:
      - name: airSpeed
        unit: m/s
        value: 110.2
      - name: altitude
        unit: m
        value: 1200.0
      - name: engineTemperature
        unit: C
        value: 90
      - name: fuelLevel
        unit: "%"
        value: 55
      - name: batteryVoltage
        unit: V
        value: 12

  - id: 3
    name: engine_sensor
    metrics:
      - name: airSpeed
        unit: m/s
        value: 105.0
      - name: altitude
        unit: m
        value: 980.0
      - name: engineTemperature
        unit: C
        value: 92
      - name: fuelLevel
        unit: "%"
        value: 48
      - name: batteryVoltage
        unit: V
        value: 11

  - id: 4
    name: fuel_sensor
    metrics:
      - name: airSpeed
        unit: m/s
        value: 115.8
      - name: altitude
        unit: m
        value: 1100.0
      - name: engineTemperature
        unit: C
        value: 87
      - name: fuelLevel
        unit: "%"
        value: 42
      - name: batteryVoltage
        unit: V
        value: 12

  - id: 5
    name: battery_sensor
    metrics:
      - name: airSpeed
        unit: m/s
        value: 115.8
      - name: altitude
        unit: m
        value: 1100.0
      - name: engineTemperature
        unit: C
        value: 87
      - name: fuelLevel
        unit: "%"
        value: 42
      - name: batteryVoltage
        unit: V
        value: 12
