#include "sensor.h"
#include <stdio.h>
#include <stdlib.h>

// Engine thermal model constants (ported from main.py prototype)
#define AMBIENT_TEMP_C   25.0f  // ambient temperature in Celsius
#define HEAT_GENERATED_W 1500.0f // heat generated by the engine in Watts
#define ENGINE_MASS_KG   120.0f // engine mass in kg
#define SPECIFIC_HEAT    450.0f // specific heat of the engine in J/(kg*C)
#define COOLING_RATE     0.02f  // cooling rate constant in 1/s

void initSensor(sensor* s, int id) {
  s->id = id;
}

void initSensorData(sensorData* d) {
  d->sensorId = 0;
  d->airSpeed = 0.0;
  d->altitude = 0.0;
  d->engineTemperature = 0;
  d->fuelLevel = 0;
  d->initialFuelLevel = 0;
  d->batteryVoltage = 0;
  d->engineTemp = 0.0f;
  d->lastUpdate_s = 0.0f;
}

void printSensorData(sensorData d) {
  printf("Sensor Id:%d\n", d.sensorId);
  printf("Air Speed:%f\n", d.airSpeed);
  printf("Altitude:%f\n", d.altitude);
  printf("Engine Temperature:%d\n", d.engineTemperature);
  printf("Fuel Level:%d\n", d.fuelLevel);
  printf("Battery Voltage:%d\n", d.batteryVoltage);
}

int sensorDataToString(sensorData d, char* buf, size_t bufSize) {
  return snprintf(buf, bufSize, "Sensor %d | Air Speed:%f Altitude:%f Engine Temp:%d Fuel:%d Battery:%d\n",
    d.sensorId, d.airSpeed, d.altitude, d.engineTemperature, d.fuelLevel, d.batteryVoltage);
}
#define FUEL_BURN_RATE 1

static int updateFuelLevel(int initialFuelLevel, int burnRate, float time_s) {
  int remaining_fuel = initialFuelLevel - (int)(burnRate * time_s);
  return remaining_fuel > 0 ? remaining_fuel : 0;
}

// One explicit Euler step of the engine thermal model:
//   dT/dt = -coolingRate * (T - ambient) + heatGenerated / (mass * specificHeat)
// Returns the temperature clamped at 0 C.
static float updateEngineTemp(float currentTemp, float timeStep) {
  float heatLoss = -COOLING_RATE * (currentTemp - AMBIENT_TEMP_C);
  float heatGain = HEAT_GENERATED_W / (ENGINE_MASS_KG * SPECIFIC_HEAT);
  float dTdt = heatLoss + heatGain;

  float nextTemp = currentTemp + (dTdt * timeStep);
  return nextTemp > 0.0f ? nextTemp : 0.0f;
}

void sensorDataUpdate(sensorData* d, float time_s) {
  // Integrate over the elapsed time since the previous update
  float timeStep = time_s - d->lastUpdate_s;
  if (timeStep < 0.0f) timeStep = 0.0f;
  d->lastUpdate_s = time_s;

  d->airSpeed = rand();
  d->altitude = rand();
  d->engineTemp = updateEngineTemp(d->engineTemp, timeStep);
  d->engineTemperature = (int)(d->engineTemp + 0.5f);
  d->fuelLevel = updateFuelLevel(d->initialFuelLevel, FUEL_BURN_RATE, time_s);
  d->batteryVoltage = rand();
}
